version: "3.0"
services:
  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
    ports:
      - 8200:8200
    privileged: true
  minio:
   image: minio/minio
   environment:
     - MINIO_ROOT_USER=admin
     - MINIO_ROOT_PASSWORD=admin123
     - MINIO_REGION_NAME=us-east-1
   ports:
     - "9000:9000"
     - "9001:9001"
   command: server --console-address ":9001" /data
   volumes:
     - minio_data:/data

volumes:
  minio_data: {}
